шлифовка
htmlacademy-htmlcss/1979299-device-33 pull request #12
Opened 2022-03-16 09:50 UTC by Shchipanov

2022-03-16 11:13 UTC, mkolotovich requested changes
Форме subscription-form в action задайте https://echo.htmlacademy.ru. В поповер тоже либо сделайте как я написал выше либо вообще уберите форму. Кнопке .button задайте текстовое описание. В этих лейблах .select тоже нет текстового описания. У этого лейбла .subscription-mail тоже нет текстового описания. В этой ссылке .htmlacademy-link тоже нет текстового описания. Тоже самое касается и этих кнопок .button-sorting и этих инпутов .auth-form-field, а также вот этого инпута .auth-input.

2022-03-16 14:42 UTC, mkolotovich requested changes
Исправьте комментарий с прошлой проверки плюс добавились новые. Элементу      <button type="button"></button>(.navigator-item-user button) задайте текстовое описание.

2022-03-16 14:42 UTC, mkolotovich commented on styles/styles.css
> +} */
верните это правило

2022-03-17 04:32 UTC, Shchipanov commented on styles/styles.css
> +} */
сделано

2022-03-17 06:19 UTC, mkolotovich requested changes
Исправьте комментарии

2022-03-17 06:19 UTC, mkolotovich commented on index.html
> +                  <span class="visually-hidden">Добавьте имя</span>
этот спан вложите внутрь лейбла

2022-03-17 06:19 UTC, mkolotovich commented on index.html
> +                <span class="visually-hidden">Введите электронную почту</span>
этот спан тоже вложите внутрь лейбла

2022-03-17 06:19 UTC, mkolotovich commented on index.html
> +            <button type="button"></button>
этой кнопке добавьте текстовое описание

2022-03-17 06:35 UTC, Shchipanov commented on index.html
> +                  <span class="visually-hidden">Добавьте имя</span>
ссделано

2022-03-17 06:37 UTC, Shchipanov commented on index.html
> +                <span class="visually-hidden">Введите электронную почту</span>
сделано

2022-03-17 06:39 UTC, Shchipanov commented on index.html
> +            <button type="button"></button>
сделано

2022-03-17 07:24 UTC, merged