Наполняет header
htmlacademy-htmlcss/1979299-device-33 pull request #2
Opened 2022-01-23 07:36 UTC by Shchipanov

2022-01-25 07:34 UTC, Shchipanov commented
завершает первую страницу index

2022-01-25 08:22 UTC, Shchipanov reviewed
на проверку первая страница

2022-01-25 10:49 UTC, mkolotovich requested changes

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <label class="visually-hidden" for="search-field">Найти</label>
Нарушен критерий HTML-04. Работоспособные формы(https://up.htmlacademy.ru/htmlcss/33/criteries#HTML). Поля формы должны находиться внутри тега `<form>`.

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +           <a class="navigation-compare" href="contacts.html">Контакты</a>
В задании указано - Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>.`

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <img class="slider-image" src="#" alt="Образец девайся Квадрокоптер">
В макете изображение находится между двумя кнопками. Предлагаю разметить в таком же порядке

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +      </section>
Этот секшн вложите внутрь предыдущего секшена

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <h2 class="visually-hidden">Описание девайса</h2>
Внутри элемента ul не может быть никаких элементов кроме li. Вынесите заголовок на уровень выше

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +             </div>
Это разметьте просто с помощью текста, текст не нужно вставлять изображением)

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +             <p class="short-description device-description">Этот обычный, на первый взгляд, квадрокоптер оснащен<br> мощным лазером, замаскированным под стандартную камеру.</p>
Тег br необходимо использовать только в случае если перенос текста как на макете невозможно сделать с помощью стилей. Здесь он избыточен, как в принципе и тег параграфа

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +         <span class="short-description more"><b>Подробнее</span>
По макету это кнопка. Плюс вы еще указали внутри тег b. Если вы это сделали то его нужно и закрыть, так как он парный

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +         <input class="select" type="radio" value="select-right">
Нарушен критерий HTML-04. Работоспособные формы(https://up.htmlacademy.ru/htmlcss/33/criteries#HTML). Поля формы должны находиться внутри тега `<form>`.

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +            <a class="devace-VR" href="#">Виртуальная<br> реальность</a>
Здесь тег br лишний

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +            <a class="devace-monopods" href="#">Моноподы<br> для селфи</a>
Здесь тег br лишний

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +      </section>
Эту секцию вложите в секцию выше

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <h2 class="visually-hidden">Описание услуги</h2>
Не понятно зачем здесь использовать скрытый заголовок, если под ним вы используете не скрытый заголовок. Предлагаю убрать скрытый заголовок

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <p class="about-us-paragraph">Мы можем доставить ваш товар в самые отдалённые<br> уголки России транспортными компаниями:</p>
Лишние теги br

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <li>
Лишний открывающий тег li

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <li>
Лишний открывающий тег li

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <span class="about-us-more"><a href="#">Подробнее о нас</a></span>
Нарушен критерий - HTML-06. Лишние элементы(https://up.htmlacademy.ru/htmlcss/33/criteries#HTML). В разметке не должно быть лишних обёрток и элементов, которые используются для оформления и могут быть заменены на псевдоэлементы. Тут использована лишняя обёртка span

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <p class="contacts-som-export">Вы можете забрать товар сами, заехав в наш офис.<br>
Лишний br

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <span class="contacts-write"><a href="#">Напишите нам</a></span>
Нарушен критерий - HTML-06. Лишние элементы(https://up.htmlacademy.ru/htmlcss/33/criteries#HTML). В разметке не должно быть лишних обёрток и элементов, которые используются для оформления и могут быть заменены на псевдоэлементы. Тут использована лишняя обёртка span

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +        <p>Подпишитесь<br>
Лишний br

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +            <p class="subscription-form-mail">
Тег p тут избыточен, инпут можно полжить внутрь лейбла

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +            длительными тест-драйвами, распаковками, а также акции,<br> спецпредложения и вот это вот всё.</p>
Этот br избыточен

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная<br> реки Карповки, 5, литера П.</p>
br здесь лишний как и тег p

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +      </section>
Тут тег address избыточен как и тег section

2022-01-25 10:49 UTC, mkolotovich commented on index.html
> +          <p class="about-text"><a class="htmlacademy-link" href="https://htmlacademy.ru/"><img class="htmlacademy-img" src="#" alt="Логотип HTML Academy"</a></p>
У тега img пропустили закрывающую скобку

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <label class="visually-hidden" for="search-field">Найти</label>
Исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +           <a class="navigation-compare" href="contacts.html">Контакты</a>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <img class="slider-image" src="#" alt="Образец девайся Квадрокоптер">
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <h2 class="visually-hidden">Описание девайса</h2>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +             </div>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +             <p class="short-description device-description">Этот обычный, на первый взгляд, квадрокоптер оснащен<br> мощным лазером, замаскированным под стандартную камеру.</p>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +         <span class="short-description more"><b>Подробнее</span>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +         <input class="select" type="radio" value="select-right">
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +            <a class="devace-VR" href="#">Виртуальная<br> реальность</a>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +      </section>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +            <a class="devace-monopods" href="#">Моноподы<br> для селфи</a>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <h2 class="visually-hidden">Описание услуги</h2>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +      </section>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <p class="about-us-paragraph">Мы можем доставить ваш товар в самые отдалённые<br> уголки России транспортными компаниями:</p>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <li>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <li>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <span class="about-us-more"><a href="#">Подробнее о нас</a></span>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <p class="contacts-som-export">Вы можете забрать товар сами, заехав в наш офис.<br>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <span class="contacts-write"><a href="#">Напишите нам</a></span>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +        <p>Подпишитесь<br>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +            <p class="subscription-form-mail">
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +            длительными тест-драйвами, распаковками, а также акции,<br> спецпредложения и вот это вот всё.</p>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная<br> реки Карповки, 5, литера П.</p>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +      </section>
исправлено

2022-01-25 14:49 UTC, Shchipanov commented on index.html
> +          <p class="about-text"><a class="htmlacademy-link" href="https://htmlacademy.ru/"><img class="htmlacademy-img" src="#" alt="Логотип HTML Academy"</a></p>
исправлено

2022-01-26 06:09 UTC, mkolotovich commented on index.html
> +        <img class="slider-image" src="#" alt="Образец девайся Квадрокоптер">
Я имел ввиду, что кнопку slider-button slider-prev необходимо поместить в секшн gallery. Просто она должна находиться перед изображением

2022-01-26 06:15 UTC, mkolotovich commented on index.html
> +         <span class="short-description more"><b>Подробнее</span>
Кнопка размечается с помощью тега button. <input type="submit" используется только для отправки формы. Здесь формы нет.

2022-01-26 06:17 UTC, mkolotovich commented on index.html
> +      </section>
Вложите эту секцию внутрь секции services

2022-01-26 06:31 UTC, mkolotovich commented on index.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная<br> реки Карповки, 5, литера П.</p>
Тег p здесь - это лишняя обёртка

2022-01-26 06:34 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с прошлой проверки. К ним я оставил комментарии

2022-01-26 11:26 UTC, Shchipanov commented on index.html
> +        <img class="slider-image" src="#" alt="Образец девайся Квадрокоптер">
здесь поторопился и невнимательность, изначально так и понял

2022-01-26 11:28 UTC, Shchipanov commented on index.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная<br> реки Карповки, 5, литера П.</p>
исправлено. спасибо учту

2022-01-26 11:47 UTC, mkolotovich requested changes
Исправьте 2 не схлопнутых замечания с первой проверки

2022-01-26 12:11 UTC, Shchipanov commented on index.html
> +         <span class="short-description more"><b>Подробнее</span>
исправлено

2022-01-26 12:18 UTC, Shchipanov commented on index.html
> +      </section>
исправил

2022-01-26 12:27 UTC, mkolotovich requested changes
Строки 152 - 154 файла index.html оберните в див и поместите этот див перед секцией about-us

2022-01-26 12:53 UTC, merged