завершает задание 2 стилизация
htmlacademy-htmlcss/1979299-device-33 pull request #5
Opened 2022-02-02 12:39 UTC by Shchipanov

2022-02-02 12:39 UTC, Shchipanov commented
завершает стилизацию двух страниц

2022-02-02 14:55 UTC, mkolotovich requested changes
Исправьте замечания

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .input-form и задайте ему font-family: Rubik; font-size: 16px;
line-height: 20px;     background: transparent;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .in-the-basket и задайте ему font-size: 14px;
line-height: 17px; background: #FFFFFF;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .visually-hidden и стилизуйте как в статье - https://htmlacademy.ru/blog/boost/frontend/short-12

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
задайте letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration: none;
задайте letter-spacing: -0.02em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .services-list a и задайте ему letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
Задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
Задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
Задайте letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
задайте letter-spacing: -0.02em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: #FFC700;
задайте letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
измените на color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration: none;
удалите это свойство, оно перезаписывает свойство выше

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .navigation-search-field и задайте ему font-family: Rubik; font-size: 16px;
line-height: 20px;     background: transparent;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .navigation-search-field::placeholder и задайте ему color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on index.html
>            <form class="subscription-form" action="#" method="post">
в лейбле уберите атрибут for. Он здесь не нужен ведь вы итак вкладываете инпут внутрь лейбла. Также в инпуте вместо id лучше использовать класс для стилизации

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор #subscription-mail и задайте ему font-family: Rubik; font-size: 18px;
line-height: 30px;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектора #subscription-mail::placeholder и задайте ему color: #444444;

opacity: 0.5;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
задайте letter-spacing: 0.2em; text-transform: uppercase;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration-line: underline;
Это свойство лишнее, уберите его

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: #FFFFFF;
задайте letter-spacing: 0.2em;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration: none;
Удалите это свойство, оно лишнее

2022-02-02 14:55 UTC, mkolotovich commented on catalog.html
> +        <a class="navigation-link" href="#">Войти</a>
Тут должен быть - Коля Петухов

2022-02-02 14:55 UTC, mkolotovich commented on catalog.html
>        </li>
Добавьте еще один пункт списка - Выйти

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
задайте color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте letter-spacing: 0.2em; color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .select-control и задайте ему font-family: Rubik; font-size: 18px;
line-height: 30px;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .catalog-filter-group:first-child input и задайте ему font-family: Rubik; font-size: 15px;
line-height: 18px;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .catalog-filter-group:first-child input::placeholder и задайте ему color: #000000;

opacity: 0.3;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .control и задайте ему line-height: 19px; color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте font-size: 16px; letter-spacing: 0.2em; color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
Задайте letter-spacing: 0.2em; text-transform: uppercase; color: #000000;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration: none;
задайте opacity: 0.3;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +    background-color: #FFC700;
задайте background: #FFE17F;

2022-02-02 14:55 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .pagination и задайте ему background: #EBEBEB;

2022-02-02 15:07 UTC, Shchipanov commented on styles/styles.css
> +
выполнено

2022-02-02 15:21 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-02 15:27 UTC, Shchipanov commented on styles/styles.css
> +    text-transform: uppercase;
исправлено

2022-02-02 15:46 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-02 15:54 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-02 15:57 UTC, Shchipanov commented on styles/styles.css
> +    text-transform: uppercase;
исправлено

2022-02-02 16:01 UTC, Shchipanov commented on styles/styles.css
> +    background-color: inherit;
исправлено

2022-02-02 16:03 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration: none;
исправлено

2022-02-02 16:09 UTC, Shchipanov commented on styles/styles.css
> +    background-color: #FFC700;
исправлено

2022-02-02 16:12 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 07:52 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 07:52 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с прошлой проверки

2022-02-03 07:53 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration: none;
исправлено

2022-02-03 07:57 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 07:58 UTC, Shchipanov commented on styles/styles.css
> +    background-color: inherit;
исправлено

2022-02-03 07:59 UTC, Shchipanov commented on styles/styles.css
> +    background-color: inherit;
исправлено

2022-02-03 08:00 UTC, Shchipanov commented on styles/styles.css
> +    background-color: #FFC700;
исправлено

2022-02-03 08:02 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration: none;
исправлено

2022-02-03 08:06 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:12 UTC, Shchipanov commented on index.html
>            <form class="subscription-form" action="#" method="post">
исправлено

2022-02-03 08:15 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:20 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:22 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:23 UTC, Shchipanov commented on styles/styles.css
> +    background-color: inherit;
исправлено

2022-02-03 08:24 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration-line: underline;
исправлено

2022-02-03 08:25 UTC, Shchipanov commented on styles/styles.css
> +    color: #FFFFFF;
исправлено

2022-02-03 08:26 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration: none;
исправлено

2022-02-03 08:27 UTC, Shchipanov commented on catalog.html
> +        <a class="navigation-link" href="#">Войти</a>
исправлено

2022-02-03 08:37 UTC, Shchipanov commented on catalog.html
>        </li>
исправлено

2022-02-03 08:38 UTC, Shchipanov commented on styles/styles.css
> +    text-transform: uppercase;
исправлено

2022-02-03 08:42 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:45 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:46 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 08:53 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 09:19 UTC, mkolotovich commented on styles/styles.css
> +    background-color: inherit;
Вы указали letter-spacing: 0.2rem;, что вычисляется в 3.2px, так как расчет идет от фонт-сайза боди, а если задать 0.2em;, что вычисляется в 4px, так как расчет идет от фонт-сайза родительского элемента

2022-02-03 09:25 UTC, mkolotovich commented on styles/styles.css
> +
Вы изменили разметку, теперь у вас нет id, а есть класс, поэтому нужно изменить селектор на .subscription-mail

2022-02-03 09:26 UTC, mkolotovich commented on styles/styles.css
> +
Вы изменили разметку, теперь у вас нет id, а есть класс, поэтому нужно изменить селектор на .subscription-mail::placeholder

2022-02-03 09:28 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration-line: underline;
Задайте font-style: normal;

2022-02-03 09:34 UTC, mkolotovich commented on styles/styles.css
> +    text-decoration: none;
Задайте color: #444444;

2022-02-03 09:35 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с первой проверки, к ним я оставил комментарии

2022-02-03 09:40 UTC, Shchipanov commented on styles/styles.css
> +    background-color: inherit;
исправлено

2022-02-03 09:45 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 09:45 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-03 09:47 UTC, Shchipanov commented on styles/styles.css
> +    text-decoration: none;
исправлено

2022-02-03 10:34 UTC, merged