попытка сверстать сетку index
htmlacademy-htmlcss/1979299-device-33 pull request #6
Opened 2022-02-07 07:11 UTC by Shchipanov

2022-02-07 08:00 UTC, mkolotovich requested changes
Селектору .pagination задайте display: flex;. Селектору .filter задайте display: flex;. В странице каталога оберните в див элементы `<h2 class="filter-title">фильтр:</h2>` и `<form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">`. Элемент `<ul class="pagination">` положите внутрь секции `<section class="sorting">`.

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
> +    width: 1040;
Не верное значение, не указана еденица измерения

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .gallery и задайте ему     display: flex

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .footer-social-list и задайте ему display: flex

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
> +    width: 444px;
задайте     display: flex;

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .product-list и задайте ему display: flex; flex-wrap: wrap;

2022-02-07 08:00 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .monopods-list и задайте ему     display: flex;

2022-02-07 08:00 UTC, mkolotovich commented on index.html
> +      <div class="footer-address-container">
Элементы футера я предлагаю разметить слелующим образом: сделать 3 строки и по 3 столбца в каждом. Так будет проще делать сетку

2022-02-08 06:46 UTC, Shchipanov commented on styles/styles.css
> +    width: 1040;
исправлено

2022-02-08 06:52 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-08 06:54 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-08 06:55 UTC, Shchipanov commented on styles/styles.css
> +    width: 444px;
исправлено

2022-02-08 06:58 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-08 06:59 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-09 17:30 UTC, Shchipanov commented on index.html
> +      <div class="footer-address-container">
сделано

2022-02-10 06:32 UTC, mkolotovich requested changes
Исправьте комментарии с прошлой проверки плюс добавились новые. Элементы `<h1 class="about-us-title">Моноподы для селфи</h1>` и `<ul class="monopods-list">` оберните в один тег для удобства построения сетки. Подвал на внутренней странице тоже разметьте как на главной

2022-02-10 06:32 UTC, mkolotovich commented on styles/styles.css
> +    width: 1440px;
Уберите это свойство. Это ширина футера в макете. Страница может быть шире чем на макете

2022-02-10 06:32 UTC, mkolotovich commented on styles/styles.css
> +    width: 1440px;
Уберите это свойство. Ширина страницы не должна быть фиксированной.

2022-02-10 06:32 UTC, mkolotovich commented on styles/styles.css
> +    width: 1160px;
уберите это свойство, не надо ограничивать ширину контента, так как в требованиях указано, что фоны которые упираются в края макета должны тянуться на всю ширину

2022-02-10 06:32 UTC, mkolotovich commented on index.html
>            <button class="gallery-more" type="button">Подробнее</button>
Эту кнопку положите внутрь дива, который идет ниже

2022-02-10 06:32 UTC, mkolotovich commented on styles/styles.css
> +    width: 1440px;
уберите ширину

2022-02-10 06:32 UTC, mkolotovich commented on styles/styles.css
> +    width: 1440px;
уберите ширину

2022-02-10 09:16 UTC, Shchipanov commented on styles/styles.css
> +    width: 1440px;
убрал

2022-02-10 09:22 UTC, Shchipanov commented on styles/styles.css
> +    width: 1440px;
убрал

2022-02-10 09:25 UTC, Shchipanov commented on styles/styles.css
> +    width: 1160px;
убрал и теперь некоторые элементы растянулись по ширине страницы

2022-02-10 09:45 UTC, Shchipanov commented on index.html
>            <button class="gallery-more" type="button">Подробнее</button>
исправлено

2022-02-10 09:48 UTC, Shchipanov commented on styles/styles.css
> +    width: 1440px;
убрал

2022-02-10 09:51 UTC, Shchipanov commented on styles/styles.css
> +    width: 1440px;
убрал

2022-02-10 10:59 UTC, mkolotovich requested changes
Исправьте замечания с первой проверки. Создайте внутри секции services обёртку и поместите контент внутрь неё. Селектору .subscription-mail задайте     width: 100%;. Селектору .navigation-search-field задайте     width: 100%;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +
Задайте margin: auto;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .device и задайте ему width: 1160px;
    margin: auto;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +page-footer-container {
Точку забыли перед селектором поставить

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +    flex-direction: column;
эти свойства не нужны

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +    margin: 0 140px;
а вместо этого задайте width: 1160px;
    margin: auto;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +    width: 810px;
задайте     display: flex;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .subscription-form label и задайте ему flex-grow: 1;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .search form и задайте ему     width: 100%;
    display: flex;

2022-02-10 10:59 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .search label и задайте ему flex-grow: 1;

2022-02-10 11:33 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-10 11:38 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-10 11:40 UTC, Shchipanov commented on styles/styles.css
> +page-footer-container {
исправлено

2022-02-10 11:41 UTC, Shchipanov commented on styles/styles.css
> +    flex-direction: column;
исправлено

2022-02-10 11:46 UTC, Shchipanov commented on styles/styles.css
> +    margin: 0 140px;
исправлено

2022-02-10 11:47 UTC, Shchipanov commented on styles/styles.css
> +    width: 810px;
исправлено

2022-02-10 13:59 UTC, Shchipanov commented on styles/styles.css
> +
исправлено но изменений не заметил

2022-02-10 14:01 UTC, Shchipanov commented on styles/styles.css
> +
исправлено

2022-02-10 14:44 UTC, mkolotovich requested changes

2022-02-10 14:44 UTC, mkolotovich commented on styles/styles.css
создайте селектор .services div и задайте ему 
    display: flex;
width: 1160px;
    justify-content: space-between;

2022-02-10 15:13 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-11 06:31 UTC, mkolotovich requested changes
Исправьте последние штрихи и приму ваш ПР)

2022-02-11 06:31 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .main-container > div и задайте ему     width: 1160px;
    margin: auto;

2022-02-11 06:31 UTC, mkolotovich commented on catalog.html
>          <section class="filter">
Создайте здесь обертку и поместите контент внутрь неё. Этой обертке задайте свойства     width: 1160px;
    margin: auto; display: flex;

2022-02-11 07:22 UTC, Shchipanov commented on styles/styles.css
> +
сделано

2022-02-11 07:30 UTC, Shchipanov commented on catalog.html
>          <section class="filter">
исправил

2022-02-11 07:40 UTC, mkolotovich commented on catalog.html
>          <section class="filter">
Здесь наоборот секцию filter-container необходимо поместить внутрь секции filter.

2022-02-11 07:41 UTC, mkolotovich requested changes
Исправьте один коммент с прошлой проверки и мердж)

2022-02-11 07:49 UTC, Shchipanov commented on catalog.html
>          <section class="filter">
ссделано

2022-02-11 09:07 UTC, mkolotovich requested changes
У селектора .filter уберите свойство     display: flex;. Оно лишнее

2022-02-11 09:07 UTC, mkolotovich commented on catalog.html
>            <div>
всё содержимое секции filter необходимо положить внутрь контейнера filter-container.

2022-02-11 09:28 UTC, merged