Завершает ДЗ Сетки компонентов на флексах
htmlacademy-htmlcss/1979299-device-33 pull request #7
Opened 2022-02-15 15:25 UTC by Shchipanov

2022-02-16 07:02 UTC, mkolotovich requested changes
Внутри секции subscription создайте обертку внутрь которой положите весь контент секции. Этой обертке задайте width: 1160px;     margin: auto;. В секции sorting создайте обертку и положите внутрь неё весь контент секции кроме блока product. Этой обертке задайте display: flex; justify-content: space-between;. Кнопки сортировки тоже оберните в один элемент для удобства построения сетки. В карточках товара оберните название товара и цену в один элемент и задайте ему display: flex; justify-content: space-between; align-items: center;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +    margin-top: 30px;
уберите это свойство и задайте его селектору .navigator-item-user

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +    width: 452px;
уберите это свойство

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +    margin-bottom: 70px;
задайте width: 1160px;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +    margin-left: 252px;
измените значение на 16.5px;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
>      justify-content: space-between;
задайте     align-items: center;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
Создайте селектор form .catalog-filter-group:first-child и задайте ему     display: flex;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .catalog-filter-group, .catalog-filter-list и задайте ему list-style-type: none

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
>      background: #EBEBEB;
задайте     width: 100%;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .pagination-item:first-child и задайте ему     margin-right: auto;

2022-02-16 07:02 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .pagination-item:last-child и задайте ему     margin-left: auto;

2022-02-16 15:18 UTC, Shchipanov commented on styles/styles.css
> +    margin-top: 30px;
выполнено

2022-02-16 15:39 UTC, Shchipanov commented on styles/styles.css
> +    margin-bottom: 70px;
исправлено

2022-02-16 15:43 UTC, Shchipanov commented on styles/styles.css
> +    margin-left: 252px;
исправлено

2022-02-16 15:45 UTC, Shchipanov commented on styles/styles.css
>      justify-content: space-between;
исправлено

2022-02-16 15:50 UTC, Shchipanov commented on styles/styles.css
выполнено

2022-02-16 15:53 UTC, Shchipanov commented on styles/styles.css
исправлено

2022-02-16 15:55 UTC, Shchipanov commented on styles/styles.css
>      background: #EBEBEB;
делал так уже и ничего не поменялось

2022-02-16 15:57 UTC, Shchipanov commented on styles/styles.css
>      background: #EBEBEB;
сорри, в последних исправлениях все понял зачем

2022-02-16 15:57 UTC, Shchipanov commented on styles/styles.css
> +
сделано

2022-02-16 16:00 UTC, Shchipanov commented on styles/styles.css
> +
сделано

2022-02-17 06:32 UTC, mkolotovich requested changes
Исправьте комментарии

2022-02-17 06:32 UTC, mkolotovich commented on styles/styles.css
> +    display: block;
это свойство уберите, а предыдущие два верните

2022-02-17 06:32 UTC, mkolotovich commented on styles/styles.css
>      margin: 0;
это свойство уберите оно перетирает предыдущее

2022-02-17 06:32 UTC, mkolotovich commented on styles/styles.css
создайте селектор .catalog > div и задайте ему     width: 1160px;

2022-02-17 06:32 UTC, mkolotovich commented on styles/styles.css
> +.subscription div {
Измените селектор на .subscription > div

2022-02-17 08:02 UTC, Shchipanov commented on styles/styles.css
> +    display: block;
сделано

2022-02-17 08:04 UTC, Shchipanov commented on styles/styles.css
>      margin: 0;
сделано

2022-02-17 08:07 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-17 08:09 UTC, Shchipanov commented on styles/styles.css
> +.subscription div {
сделано

2022-02-17 08:17 UTC, merged