Делает отступы первой страницы
htmlacademy-htmlcss/1979299-device-33 pull request #9
Opened 2022-02-24 11:27 UTC by Shchipanov

2022-02-25 10:45 UTC, mkolotovich requested changes
Селектору .contacts-phone-link задайте     text-decoration: underline;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
> +    border-radius: 50px 0px 0px 50px;
задайте     border: 2px solid;
    border-right: none;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
> +    border-radius: 0 50px 50px 0;
задайте border: 2px solid;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
>      text-align: center;
Уберите свойство background-color. Необходимо создать псевдоэлемент которому нужно задать этот background-color и размеры как на макете.

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .devace-item:nth-child(2) .devace-link и задайте ему     width: 129px;
    display: block;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
> +    background-color: #FFE17F;
Убирайте это свойство. Здесь тоже нужно создать псевдоэлемент которому необходить задать этот фоновый цвет и размеры как на макете.

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
>  .services-list {
Необходимо создать псевдоэлемент для боковой полоски и стилизовать как на макете

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .order-icon-post и задайте ему     margin-right: 42px;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
>      padding: 0;
задайте list-style: none; и цвет удалите. Эти кружочки напротив каждого элемента как на макете необхимо тоже делать псевдоэлементами.

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
>      background-color: #FFE17F;
Уберите это свойство. Создайте псевдоэлемент и задайте ему этот цвет и размеры как на макете

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .contacts > .about-us-paragraph и задайте ему width: 513px;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
> +    padding: 11px 447px 14px 16px;
задайте background: transparent;
    border: none;
    border-bottom: solid 3px #C4C4C4;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .subscription-form .button и задайте ему border: 3px solid #CECECE;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .its-free и задайте ему align-items: center;
    display: flex;

2022-02-25 10:45 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .its-free .about-us-paragraph и задайте ему width: auto

2022-02-25 11:51 UTC, Shchipanov commented on styles/styles.css
> +    border-radius: 50px 0px 0px 50px;
выполнил

2022-02-25 11:54 UTC, Shchipanov commented on styles/styles.css
> +    border-radius: 0 50px 50px 0;
выполнил

2022-02-25 12:00 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-25 12:06 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-25 12:08 UTC, Shchipanov commented on styles/styles.css
> +    padding: 11px 447px 14px 16px;
выполнил

2022-02-25 12:10 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-25 12:13 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-25 14:16 UTC, Shchipanov commented on styles/styles.css
сделано

2022-02-27 19:58 UTC, mkolotovich commented on styles/styles.css
>      color: #444444;
задайте свойство     text-decoration-skip-ink: none;

2022-02-27 19:58 UTC, mkolotovich commented on styles/styles.css
> +    content: ">";
измените свойства на  content: "";
    background-image: url(../images/catalog-images/breadcrumbs.svg);
    width: 4px;
    height: 7px;
    position: absolute;

2022-02-27 19:58 UTC, mkolotovich commented on styles/styles.css
>      padding: 0;
задайте position: absolute;

2022-02-27 19:58 UTC, mkolotovich commented on styles/styles.css
> +    background-color: #FFE17F;
псевдоэлемент задайте z-index: -1;, а элементу z-index: 0;

2022-02-27 20:12 UTC, mkolotovich requested changes

2022-02-27 20:12 UTC, mkolotovich commented on styles/styles.css
> +    padding: 18px 39px;
измените на     padding: 15px 39px;

2022-02-27 20:12 UTC, mkolotovich commented on styles/styles.css
>  .about-us-canteiner .about-us-paragraph {
Измените селектор на .about-us-canteiner > .about-us-paragraph

2022-02-27 20:12 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с первой проверки, плюс добавились новые. Селектору .subscription-form задайте flex-shrink: 0;

2022-02-28 11:58 UTC, mkolotovich requested changes
Также нужно разметить и стилизовать пункты меню при ховере на катлог товаров.

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +    margin-left: 60px;
задайте     padding: 2px 1.5px;

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +.footer-logo-container:focus {
измените селекторы на селекторы вида .footer-logo-container a:focus

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +}
Создайте селектор .gallery-more:disabled и задайте стили как на макете

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селекторы для состояний .input-form и задайте им соответсвующие стили

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
>      color: #000000;
задайте opacity: 0.3;

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте и стилизуйте селекторы для состояний .navigation-search-field

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +
Создайте и стилизуйте селекторы для состояний .navigator-item .navigation-link

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы .catalog-user img и задайте ему состояния как на макете

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +    margin-top: 55px;
задайте height: 64px;

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы .footer-social-item a и задйте им стили для состояний

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +}
Создайте селекторы для состояний .htmlacademy-link и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы для состояний .navigation-link-user и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы для состояний .fotter-scroll-link и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы для состояний .footer-contacts-address-phone и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы для состояний .devace-images и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
Создайте селекторы для состояний .order и стилизуйте их

2022-02-28 11:58 UTC, mkolotovich commented on styles/styles.css
> +.services-delivery-item a {
Вместо селектора по тегу здесь лучше использовать селектор по классу, по тому как при переключении табов стили сломаются. Нужно иметь нечто вроде класса active и стилизовать по нему

2022-03-02 06:54 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с предыдущей проверки

2022-03-02 06:54 UTC, mkolotovich commented on styles/styles.css
> +    grid-row: repeat(3, 100%);
Такого свойства не существует. Удалите его

2022-03-02 06:54 UTC, mkolotovich commented on styles/styles.css
> +    display: grid;
Меню по умолчанию должно быть скрыто, поэтому удалите это свойство

2022-03-02 06:54 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .catalog-user-item:last-child и задайте ему grid-column: 1;

2022-03-02 06:54 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .footer-logo-container a и задайте ему    
 width: 149px;
    justify-content: center;
    height: 40px;
    align-items: center;
    display: flex;

2022-03-02 06:54 UTC, mkolotovich commented on styles/styles.css
> +.gallery-more:disabled:focus {
В этих селекторах уберите псевдоэлемент :disabled

2022-03-02 08:26 UTC, mkolotovich requested changes
В элементе `<img class="order-icon" src="images/main-images/delivery/delivery-car.svg" width="125" height="100" alt="Иконка доставка грузовик">` вставляйте только изображение грузовика без фоновой цвета.

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    opacity: 0.3;
удалите это свойство

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    color: #FFFFFF;
измените значение на rgba(255, 255, 255, 0.3)

2022-03-02 08:26 UTC, mkolotovich commented on index.html
>              <input class="input-form" type="submit" value="Найти">
Этот элемент тоже оберните в лейбл и стили для фокуса задавайте на лейбле

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +.input-form:visited {
измените селектор на .input-form:disabled

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +.navigation-search-field:focus {
Этот селектор измените на .search label:focus

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    border: 2px solid #AF4FFF;
Это свойство измените на     outline: 2px solid #AF4FFF;
    outline-offset: 2px;

2022-03-02 08:26 UTC, mkolotovich commented on index.html
> +            </svg>
Этот элемент положите внутрь лейбла после инпута

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .navigation-search-field:disabled + svg и задайте ему opacity: 0.3;

2022-03-02 08:26 UTC, mkolotovich commented on index.html
> +            <img src="images/header-images/inter.svg" width="13" height="12" alt="Вход зарегистрированного пользователя">
Это изображение и в следующих элементах этого списка изображения сделайте псевдоэлементами

2022-03-02 08:26 UTC, mkolotovich commented on index.html
> +            <img src="images/header-images/push-catalog.svg" width="50" height="50" alt="ссылка на выбор товара">
этот элемент вставьте с помощью тега svg, чтобы ему можно было задавать стили

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    background-image: "../images/footer-images/logo-htmlacademy-hover.svg";
Можно вставить изображение вектором и просто его перекрашивать при наведении

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    height: 33px;
Из-за этих свойств при ховере логотип прыгает

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    opacity: 0.3;
в макете здесь значение 0.6

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    opacity: 0.6;
в макете здесь значение 0.3

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    border: 2px solid #AF4FFF;
измените свойство на outline

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    border: 2px solid #AF4FFF;
измените свойство на outline

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    border: 2px solid #AF4FFF;
измените свойство на outline

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
>      color: #FFFFFF;
задайте line-height: 20px;

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
>      justify-content: space-between;
задайте     align-items: center;

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +    opacity: 0.6;
в макете значение 0.3

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
> +.devace-images:active {
Измените селектор на devace-item:active

2022-03-02 08:26 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .devace-item:focus и задайте ему стили как на макете

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
> +    opacity: 0.3;
удалите это свойство и задайте его селектору .social-link:active::before

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
> +social-link:focus {
пропустили точку перед селектором

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
> +
задайте     display: flex;
    width: 119px;
    height: 37px;
    align-items: center;
}

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
> +    margin-bottom: 61px;
уберите это свойство и задайте его .footer-social-container

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
> +    margin-bottom: 77px;
уберите это свойство

2022-03-04 12:22 UTC, mkolotovich commented on index.html
>          <img class="order-icon-post" src="images/main-images/delivery/deliveri-i.svg" width="40" height="40" alt="знак после ссылки доставки">
вставьте только букву i без круга

2022-03-04 12:22 UTC, mkolotovich commented on styles/styles.css
буква i должна становиться темнее при ховере

2022-03-04 12:58 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с предыдущих проверов плюс добавились новые

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +    outline: 2px solid #AF4FFF;
задайте     outline-offset: 2px;

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +    color: #FFE17F;
измените значение на rgba(255, 225, 127, 0.5);

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +.services-delivery-item a:disabled {
Такого состояния нет в макете. В макете есть состояние Нажатие и Фокус

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +.gallery-more:focus {
измените селектор на .gallery-more:focus-visible

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +   border: 2px solid #AF4FFF;
измените свойство на outline

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +
создайте селектор .navigation-search-field:focus-visible и задайте ему     outline: none;

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +
создайте селектор .devace-link:focus-visible и задайте ему outline: none;

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +    display: block;
измените на display: grid; и задайте  z-index: 1;

2022-03-04 12:58 UTC, mkolotovich commented on styles/styles.css
> +
создайте стили состояний для элемента .navigator-item-user .navigation-icon

2022-03-05 12:41 UTC, mkolotovich requested changes

2022-03-05 12:41 UTC, mkolotovich commented on styles/styles.css
>  }
удалите это правило, оно дублируется ниже

2022-03-05 12:41 UTC, mkolotovich commented on styles/styles.css
> +  border-radius: 0;
удалите это свойство и создайте еще один псевдоэлемент для задания состояния фокуса

2022-03-06 22:02 UTC, mkolotovich requested changes
Исправьте 5 не схлопнутых комментариев с предыдущих проверок

2022-03-07 20:56 UTC, mkolotovich requested changes
Исправьте комментарии которые я вам написал в телеграме

2022-03-08 15:14 UTC, merged